### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by 121262** [OpenDataLab-Zambia/website#4]
Can we use HTML or Java for our site here?

**Comment by marrienk** [comment]
Currently the website is built with a static website building tool called [Hugo](https://gohugo.io/). Builds are done and the website is hosted by the service [Netlify](https://www.netlify.com/). All these are usable free of charge and relatively easy to use. 

Using plain html would make the website harder to manage further down the road as people would need to know it’s syntax as opposed to writing simple markdown.

the design of the website can easily be changed see #3 for a link to the official these selection for Hugo.

ps: I guess you meant JavaScript instead of Java

**Comment by 121262** [comment]
Okey great well understood @marrienk
